#!/bin/bash

source \
    <(curl -s http://$INSTALL_HOST/arch_vars)

source \
    <(curl -s http://$INSTALL_HOST/arch_fn)

bash $OPT \
    <(curl -s http://$INSTALL_HOST/arch_stage1)

arch-chroot /mnt bash $OPT \
    <(curl -s http://$INSTALL_HOST/arch_stage2)

bash $OPT \
    <(curl -s http://$INSTALL_HOST/arch_unmount)
