#!/bin/bash -e

_cmd_ env | grep ^INSTALL_

configure_disk

echo -e '\n[options]\nILoveCandy' >> /etc/pacman.conf
_cmd_ pacman --sync --refresh --noconfirm --color always reflector
_cmd_ reflector --country NL --fastest 10 --protocol http --sort rate --save /etc/pacman.d/mirrorlist

_cmd_ pacstrap /mnt ${INSTALL_PACKAGES}

_cmd_ genfstab -L -p /mnt > /mnt/etc/fstab

case "${INSTALL_DISK_ENCRYPTION}" in
    luks)
        _cmd_ mv -v /tmp/luks.keys /mnt/etc
        _cmd_ mv -v /tmp/crypttab /mnt/etc/crypttab.initramfs
        ;;
esac
