#!/bin/bash -e

configure_disk() { # plain bios mbr
    partition "${INSTALL_DISK}" "mbr" \
        "2  +0:+8G      8300    root    ext4    /" \
        "1  1M:+1023M   8300    boot    ext4    /boot" \
        "3  +0:+5G      8300    home    ext4    /home" \
        "4  +0:+2G      8200    swap    swap    -"
}


INSTALL_DISK="/dev/sda"
INSTALL_DISK_ENCRYPTION="none"
INSTALL_GRUB_FIRMWARE="bios"
INSTALL_GRUB_CMDLINE="resume=/dev/sda4"

INSTALL_HOST="${1:-https://raw.githubusercontent.com/j0057/arch/vbox}"
INSTALL_HOSTNAME="arch-dev"

INSTALL_PACKAGES="
    base grub
    ifplugd
    ntp haveged
    tmux vim-minimal htop lsof strace bind-tools traceroute openssl mc
    openssh python2 lsb-release"
INSTALL_SERVICES="
    netctl-ifplugd@net0.service
    netctl-ifplugd@net1.service
    sshd.service
    multi-user.target"

INSTALL_INTERFACES="
    net0 06:00:0a:65:14:ca
    net1 02:00:0a:65:14:ca"
INSTALL_NETCTL="net0-dhcp net1-static"
INSTALL_NETCTL_NET1_ADDR="10.101.20.202/16"

INSTALL_TZNAME="Europe/Amsterdam"
INSTALL_LOCALE="en_US.UTF-8 UTF-8"

INSTALL_PASSWORD="root"

source <(curl -s "${INSTALL_HOST}/arch_stage0")
