#!/bin/bash

INSTALL_PACKAGES=$(sed 's/\s\+/ /g ; s/^\s*//' <<< "${INSTALL_PACKAGES//$'\n'/ }")
INSTALL_SERVICES=$(sed 's/\s\+/ /g ; s/^\s*//' <<< "${INSTALL_SERVICES//$'\n'/ }")

for var in $(env | sed -n '/^INSTALL_/s/=.*//p'); do
    read -p "$var: " -e -i "${!var}" $var 0<&4
done

export INSTALL_DISK_ENCRYPTION="luks"
export INSTALL_GRUB_DISK="${INSTALL_GRUB_DISK:-/dev/sda}"
export INSTALL_GRUB_CMDLINE="${INSTALL_GRUB_CMDLINE:-quiet}"

message "Loading functions"
source <(curl -s http://${INSTALL_HOST}/arch_fn)

message "Starting stage 1"
bash -e <(curl -sv "http://${INSTALL_HOST}/arch_stage1")

message "Starting stage 2 in chroot"
arch-chroot /mnt bash -e <(curl -sv "http://${INSTALL_HOST}/arch_stage2")

message "Unmounting"
umount -R /mnt
swapoff -a

case "${INSTALL_DISK_ENCRYPTION}" in
    luks)
        lsblk -P \
            | sed -rn '/TYPE="crypt"/ { s/^NAME="([^ ]*)" .*$/\1/ ; p }' \
            | xargs -n 1 cryptsetup close
        ;;
esac
