#!/bin/bash

source \
    <(curl -s http://$INSTALL_HOST/arch_vars)

source \
    <(curl -s http://$INSTALL_HOST/arch_fn)

bash $OPT \
    <(curl -s http://$INSTALL_HOST/arch_stage1)

arch-chroot /mnt bash $OPT \
    <(curl -s http://$INSTALL_HOST/arch_stage2)

# unmount filesystems and swaps
umount -R /mnt
swapoff -a

# close device mapper stuff
if [ $INSTALL_DISK_ENCRYPTION = luks ]; then
    lsblk -P \
        | sed -rn '/TYPE="crypt"/ { s/^NAME="([^ ]*)" .*$/\1/ ; p }' \
        | xargs -n 1 cryptsetup close
fi
