#!/bin/bash -e

configure_disk() {
    partition "${INSTALL_DISK}" "mbr" \
        "2  +0:+12G     8300    root    ext4    /" \
        "1  1M:+1023M   8300    boot    ext4    /boot" \
        "3  +0:+96G     8300    home    ext4    /home" \
        "4  +0:+2G      8200    swap    swap    -"
}

INSTALL_DISK="/dev/sda"
INSTALL_DISK_ENCRYPTION="none"
INSTALL_GRUB_FIRMWARE="bios"
INSTALL_GRUB_CMDLINE="resume=/dev/sda4"

INSTALL_HOST="${1:-j0057.github.io/arch}"
INSTALL_HOSTNAME="muon"

INSTALL_INTERFACES="net0 00:27:0e:01:9c:0c dhcp"

INSTALL_TZNAME="Europe/Amsterdam"
INSTALL_LOCALE="en_US.UTF-8 UTF-8"

INSTALL_PACKAGES="
    base grub ifplugd
    lsb-release openssh python2
    base-devel git"

INSTALL_SERVICES="
    netctl-ifplugd@net0.service
    sshd.service
    multi-user.target"

INSTALL_PASSWORD="root"

source <(curl -s "http://${INSTALL_HOST}/arch_stage0")
