#!/bin/bash -e

configure_disk() {
    partition "${INSTALL_DISK}" "gpt" \
        "1  1M:+1M      ef02    bios    -       -" \
        "3  +0:+16G     8300    root    ext4    /" \
        "2  +0:+256M    8300    boot    ext4    /boot" \
        "4  +0:0        8300    home    ext4    /home"
}

INSTALL_DISK="/dev/sda"
INSTALL_DISK_ENCRYPTION="none"
INSTALL_GRUB_FIRMWARE="bios"
INSTALL_GRUB_CMDLINE=""

INSTALL_INTERFACES="
    net0 00:01:c0:18:06:39
    net1 00:01:c0:18:27:84
    net2 00:01:c0:18:27:85
    net3 00:01:c0:18:27:86"
INSTALL_NETCTL="net0-dhcp"

INSTALL_HOST="${1:-j0057.github.io/arch}"
INSTALL_HOSTNAME="photon"

INSTALL_TZNAME="Europe/Amsterdam"
INSTALL_LOCALE="en_US.UTF-8 UTF-8"

INSTALL_PACKAGES="
    base grub ifplugd
    haveged ntp
    lsb-release openssh python2"

INSTALL_SERVICES="
    netctl-ifplugd@net0.service
    sshd.service
    multi-user.target"

INSTALL_PASSWORD="root"

source <(curl -s "http://${INSTALL_HOST}/arch_stage0")
