#!/bin/bash -e

exec &> >(tee install.log)

configure_disk() {
    # "128GB" = 128035676160 B = 119 GiB + 248 MiB + 344 KiB + 0 B
    partition "$INSTALL_DISK" "gpt" \
        "3  +0:+32G     8300    strange_root    ext4    /" \
        "1  1M:+760M    8300    strange_boot    ext4    /boot" \
        "2  +0:+511M    ef00    strange_efi     vfat    /boot/efi" \
        "4  +0:+70G     8300    strange_home    ext4    /home" \
        "5  +0:+16G     8200    strange_swap    swap    -"
}

INSTALL_DISK="/dev/sda"
INSTALL_DISK_ENCRYPTION="none"
INSTALL_GRUB_FIRMWARE="uefi"
INSTALL_GRUB_CMDLINE="resume=/dev/disk/by-label/strange-swap"

INSTALL_HOST="${1:-https://j0057.github.io/arch}"
INSTALL_HOSTNAME="strange"

INSTALL_INTERFACES="
    net0    ec:a8:6b:ff:ce:dc   dhcp
    wifi0   a0:a8:cd:2d:fc:3a   pk28"

INSTALL_TZNAME="Europe/Amsterdam"
INSTALL_LOCALE="en_US.UTF-8 UTF-8"

INSTALL_PACKAGES="
    base
    grub
    efibootmgr
    ifplugd
    wpa_actiond
    wpa_supplicant
    openssh
    vim
    tmux
    htop
    mc
    retroarch
    retroarch-assets-xmb
    "

INSTALL_SERVICES="
    netctl-ifplugd@net0.service
    netctl-auto@wifi0.service
    sshd.service
    multi-user.target
    "

INSTALL_PASSWORD="root"
INSTALL_PK28_PASSWORD="password"

INSTALL_PYTHON27_PIP="0"

source <(curl -s "${INSTALL_HOST}/arch_stage0")
